#!/bin/bash
#####################################################
#
# Description: creates a pack for neomanis project
# Author: Arno68000
# Date: 2023
# Version: 1.0.0
#
####################################################

show_help(){
	echo "
		Description:	Creates a pack for neomanis project

		Usage: 		pack [options]...

		Options:
		                --keep/-k:	keep actual version from package.json
				--help:		show help
	"
}
check_result(){
	if [ ${1} -ne 0 ]; then
		exit 1
	fi
}
shuffle(){
	echo $(shuf -i 99-999 -n1)
}
change_package_version(){
	new_version="${2}"
	if [ -z "${new_version}" ]; then
		new_version=$(echo "$(shuffle).$(shuffle).$(shuffle)")
	fi
	sed -i "s|\(\"version\": \"\)\(.*\)\(\"\)|\1${new_version}\3|g" ${1}
}

rm_build_dir(){
	build_dir="${PWD}/build"
	if [ -d ${build_dir} ]; then
		rm -rf ${build_dir}
		check_result $?
	fi
}
rm_old_packs(){
	ls | grep "neomanis*" | while read -r file; do 
		if [ -f "${PWD}/${file}" ]; then
			rm "${PWD}/${file}"
			check_result $?
		fi
	done
}

main(){
	rm_build_dir
	rm_old_packs
	package="${PWD}/package.json"
	if [ ! -f ${package} ]; then
		echo -e "\033[31mError:\033[0m no package.json"
		exit 1
	fi
	old_version=$(grep -e 'version' "${package}" | sed -e 's/[^0-9.]*//g')
	echo "Current version: $old_version"

	if [ -z "${1}" ]; then
		change_package_version "${package}"
	fi

	yarn build
	if [ $? -ne 0 ]; then
		echo -e "\033[31mError:\033[0m build failed"
	fi

	yarn pack
	if [ $? -ne 0 ]; then
		echo -e "\033[31mError:\033[0m pack bundle failed"
	fi

	#restoring package.json if necessary
	if [ -z "${1}" ]; then
		change_package_version "${package}" "${old_version}"
	fi
}

keep=""
if [ ! -z "${1}" ]; then
	if [ "${1}" == "--help" ]; then
		show_help
		exit 0
	elif [[ "${1}" =~ ^(-k|--keep)$ ]]; then
		keep="true"
	else
		echo -e "\033[31mError:\033[0m option '$1' not available, please use --help for documentation"
		exit 1
	fi
fi
echo -e "\033[32mStarting...\033[0m"
main $keep
echo -e "\033[32mDone\033[0m"
exit 0
